In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

> # Lab 2_1 >> To convert a list of numeric values into a one-dimensional NumPy array

In [2]:
import numpy as np

a=[1,2,3,4,5]
print("Original Array List of one dimensional >> ",a)

b=np.array(a)
print("The Array List of the one dimensional >> ",b)


Original Array List of one dimensional >>  [1, 2, 3, 4, 5]
The Array List of the one dimensional >>  [1 2 3 4 5]


> #   Lab 2_2 >> to create a 3x3 matrix with values ranging from 2 to 10

In [3]:
import numpy as np
 

print(" Array list using arange function",np.arange(2, 10), "\n")

 Array list using arange function [2 3 4 5 6 7 8 9] 



> #  **Lab 2_3** >>  to append values at the end of an array

In [4]:
import numpy as np

a=np.array([1,3,5,7])

print("Without Appending at the end of the array >> ",a)

b=np.append(a,9)

print("With Appending at the end of the array >> ",b)

Without Appending at the end of the array >>  [1 3 5 7]
With Appending at the end of the array >>  [1 3 5 7 9]


> # Lab 2_4  >> To create another shape from an array without changing its data

In [5]:
a=np.array([2,4,6,8,10,12])
b=np.reshape(a,(3,2))

print(" >>This is a 3*2 dimensional array \n \n",b)
print("\n")
c=np.reshape(a,(2,3))

print(" >>This is a 2*3 dimensional array \n \n ",c)



 >>This is a 3*2 dimensional array 
 
 [[ 2  4]
 [ 6  8]
 [10 12]]


 >>This is a 2*3 dimensional array 
 
  [[ 2  4  6]
 [ 8 10 12]]
